[[SIRIUS]]
arch = "aarch64"
git-tree-sha1 = "29454650caef1efe538edc69e6b7390aea3b6928"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[SIRIUS.download]]
    sha256 = "ee4b7f46abbcb02f65765d627fe3b5f3f55878b97df4cb93b2785f7bb7b1d74a"
    url = "https://github.com/JuliaBinaryWrappers/SIRIUS_jll.jl/releases/download/SIRIUS-v7.9.0+0/SIRIUS.v7.9.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[SIRIUS]]
arch = "aarch64"
git-tree-sha1 = "38de94b0825d9a261e9531e535870219ebd24fc3"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[SIRIUS.download]]
    sha256 = "9e0185dc5cacd70e559846f9a8e2cc9e1dc1aef831ceb9b59e581f4fe449a210"
    url = "https://github.com/JuliaBinaryWrappers/SIRIUS_jll.jl/releases/download/SIRIUS-v7.9.0+0/SIRIUS.v7.9.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[SIRIUS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83fb8295490138b18eb9e58d73935c6ca024325c"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SIRIUS.download]]
    sha256 = "8452e63da36cfc37648f4ce62894723a1238ef8d292f6140cd0560006da93e92"
    url = "https://github.com/JuliaBinaryWrappers/SIRIUS_jll.jl/releases/download/SIRIUS-v7.9.0+0/SIRIUS.v7.9.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[SIRIUS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "117b454c352208a6b29da4f2922406bc3256fce6"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SIRIUS.download]]
    sha256 = "27128e9a335e8410f8a6983d690c46d2e6d35e54ff468b8f52921121dc72b7df"
    url = "https://github.com/JuliaBinaryWrappers/SIRIUS_jll.jl/releases/download/SIRIUS-v7.9.0+0/SIRIUS.v7.9.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[SIRIUS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eed02863b55a1ebcbd45852b009b21dd5176dcd"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[SIRIUS.download]]
    sha256 = "19d3d9913398e33033346fc73c1c0b5d6f06535a65cab4c940e3bea7584181a2"
    url = "https://github.com/JuliaBinaryWrappers/SIRIUS_jll.jl/releases/download/SIRIUS-v7.9.0+0/SIRIUS.v7.9.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[SIRIUS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f91e66c5a8b8e0d17b5a15f47014084e536fa357"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[SIRIUS.download]]
    sha256 = "77b0cce594386f3d1f3b7807249169212fc38611d505d0ea68bf4d1d37b34f06"
    url = "https://github.com/JuliaBinaryWrappers/SIRIUS_jll.jl/releases/download/SIRIUS-v7.9.0+0/SIRIUS.v7.9.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
